{{- if .Values.gitExternalSecrets.enabled }}
{{- $secretStoreRefName := .Values.gitExternalSecrets.secretStoreRefName | default "" -}}
{{- $secretStoreRefKind := .Values.gitExternalSecrets.secretStoreRefKind | default "" -}}
{{- $useHttp := .Values.gitExternalSecrets.useHttp | default false -}}
{{- $useGitHubApp := .Values.gitExternalSecrets.useGitHubApp | default false -}}
{{- $usePrivateKey := .Values.gitExternalSecrets.usePrivateKey | default false -}}
{{- $clusterGitSecrets := .Values.gitExternalSecrets.externalSecrets | default dict }}

{{- range $externalSecretName, $externalSecret := $clusterGitSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecretName }}
spec:
  secretStoreRef:
    kind: {{ $externalSecret.secretStoreRefKind | default $secretStoreRefKind }}
    name: {{ $externalSecret.secretStoreRefName | default $secretStoreRefName  }}
  refreshInterval: "1m"
  target:
    name: {{ $externalSecret.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Labels
        literal: "argocd.argoproj.io/secret-type: {{default "repository" $externalSecret.secretType }}"
      data:
        type: "git"
        {{- if  $externalSecret.gitUrl }}       
        url: {{ $externalSecret.gitUrl }}
        {{- else }}
        url: "{{`{{ .url }}`}}"
        {{- end }}
        {{- if $externalSecret.useHttp | default $useHttp }}
        username: "{{`{{ .username }}`}}"
        password: "{{`{{ .password }}`}}"
        {{- else if $externalSecret.usePrivateKey | default $usePrivateKey }}
        insecureIgnoreHostKey: "true"
        sshPrivateKey: "{{`{{ .private_key }}`}}"
        {{- else if $externalSecret.useGitHubApp | default $useGitHubApp }}
        githubAppID: "{{`{{ .github_app_id }}`}}"
        githubAppInstallationID: "{{`{{ .github_app_installation_id }}`}}"
        githubAppPrivateKey:  "{{`{{ .github_private_key }}`}}"
        {{- end }}
  dataFrom:
    - extract:
        conversionStrategy: {{ default "Default" $externalSecret.conversionStrategy }}
        metadataPolicy: {{ default "None" $externalSecret.metadataPolicy }}
        key: {{ $externalSecret.secretManagerSecretName }}
        decodingStrategy: Auto
---
{{- end }}
{{- end }}
