# applicationSets.yaml
releases:
  globals:
    # if we use the chart repo we need to be conected to remote
    chartRepoUrl: https://github.com/markoskandylis/gitops-bridge-helm-charts
    chartRepoPath: application-sets
    chartRepoRevision: main
    chartRepo: "12345678901.dkr.ecr.eu-west-2.amazonaws.com"
    ecrChartName: "application-sets"
    version: 0.3.1
  addons:
    - releaseName: "default"
      use_helm_repo_path: "true"
  monitoring:
    - releaseName: "default"
      use_helm_repo_path: "true"
  resources:
    - releaseName: "default"
      use_helm_repo_path: "true"
  fleet:
    - releaseName: "default"
      use_helm_repo_path: "true"
