# ArgoCD Service Required for Ingress with AWS alb Controller
{{- if eq .Values.enableIngress "true" }}
{{- if .Values.argoService }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: argogrpc
  name: {{.Values.argoService.argoIngressServiceName }}
spec:
  ports:
    - name: "443"
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{.Values.argoService.argoServerSericeName }}
  sessionAffinity: None
  type: NodePort
{{- end }}
{{- end }}